### PR TITLE
Avoid NPE when match list is empty

### PR DESCRIPTION
**Pull request by SomewhatDisoriented**

### CODE REVIEW

**Comment by robrua** [comment]
Hey, thanks for the PR. Would you mind also applying this change to all other appropriate overloadings of "getMatchList" before I merge it?

**Comment by SomewhatDisoriented** [comment]
Sure, I won't have access to a computer until Sunday but I can fix it after
that.

**Comment by SomewhatDisoriented** [comment]
There we go. @robrua

**Comment by robrua** [comment]
Hey - sorry for being so slow on this. I'd like to merge in 807f966 if you wouldn't mind rolling it back to that - the DTO objects are supposed to reflect the exact response from the API with no usability changes, so I don't want to return empty lists when nothing was sent.

**Comment by SomewhatDisoriented** [comment]
Okay yeah, that makes sense. Reversing the last commit now.

**Comment by robrua** [comment]
Thanks for the PR!

**Comment by SomewhatDisoriented** [comment]
You're welcome. :)

**Pull request merged**
